function gen_crc_assigns(poly_hex, crc_width, data_width, out_file)
% GEN_CRC_ASSIGNS  Generate a Verilog module with explicit assign statements
%                  for a parallel CRC engine.
%
% Use this when your synthesis tool does not support SystemVerilog parameter
% functions (e.g. older Quartus II, ISE, or strict Verilog-2001 flows).
%
% USAGE
%   gen_crc_assigns()
%       DVB CRC-32, 64-bit parallel, writes 'crc32_par64.v' in current folder
%
%   gen_crc_assigns('04C11DB7', 32, 64, 'crc32_par64.v')
%       Same as above, explicit arguments
%
%   gen_crc_assigns('04C11DB7', 32, 8,  'crc32_par8.v')
%       DVB CRC-32, 8-bit parallel (one byte per clock)
%
%   gen_crc_assigns('D5', 8, 64, 'crc8_par64.v')
%       DVB CRC-8 (MPEG-2 TS), 64-bit parallel
%
% ARGUMENTS
%   poly_hex   – Polynomial as a hex string WITHOUT leading '0x'.
%                Bit 0 = coefficient of x^1, bit (crc_width-1) = x^crc_width.
%                DVB CRC-32 : '04C11DB7'
%                DVB CRC-8  : 'D5'
%   crc_width  – CRC register width in bits (32 or 8 for DVB)
%   data_width – Number of data bits processed per clock cycle.
%                Must divide evenly into your frame size for best efficiency.
%                Common choices: 8, 16, 32, 64, 128.
%   out_file   – Output filename (string). Defaults to 'crc<W>_par<D>.v'.
%
% OUTPUT
%   A Verilog-2001 combinational module:
%       module crc<crc_width>_par<data_width> (
%           input  wire [crc_width-1:0]  crc_in,
%           input  wire [data_width-1:0] data_in,
%           output wire [crc_width-1:0]  crc_out
%       );
%   with one explicit 'assign crc_out[i] = ...' per CRC bit.
%   Plug this as a sub-module into the registered wrapper in crc32_parallel.v.
%
% POLYNOMIAL BIT ORDER
%   The LFSR feedback polynomial is stored WITHOUT the leading x^n term.
%   Example: CRC-32 = x^32 + x^26 + ... + x + 1
%     stored as 32'h04C11DB7 where bit0 = coefficient of x^1.
%
% EXAMPLE — 42 000-bit DVB frame at 64 bits/cycle:
%   gen_crc_assigns('04C11DB7', 32, 64, 'dvb_crc32_par64.v')
%   % Frame latency: ceil(42000/64) = 657 clock cycles  (vs 42 000 serial)

    % ------------------------------------------------------------------ %
    % 0. Default arguments
    % ------------------------------------------------------------------ %
    if nargin < 1 || isempty(poly_hex),   poly_hex   = '04C11DB7'; end
    if nargin < 2 || isempty(crc_width),  crc_width  = 32;         end
    if nargin < 3 || isempty(data_width), data_width = 64;         end
    if nargin < 4 || isempty(out_file)
        out_file = sprintf('crc%d_par%d.v', crc_width, data_width);
    end

    poly = hex2dec(poly_hex);   % convert polynomial to integer

    % ------------------------------------------------------------------ %
    % 1. Build the parallel XOR transformation matrix
    %
    %    We track which input bits affect each output CRC bit after
    %    data_width serial LFSR steps.
    %
    %    rows(i)  is an integer whose bit j = 1 means:
    %       "input bit j contributes to output CRC bit i"
    %    Input bits 0..crc_width-1  = current CRC state
    %    Input bits crc_width..end  = data bits (MSB-first order)
    % ------------------------------------------------------------------ %
    rows = zeros(1, crc_width, 'uint64');   % one integer per CRC output bit

    % Initialise as identity (CRC bit i depends only on CRC input bit i)
    for i = 0 : crc_width-1
        rows(i+1) = bitshift(uint64(1), i);
    end

    for step = 0 : data_width-1
        % Data bit index in the input vector for this LFSR step.
        % MSB of data_in enters first → step 0 uses data_in[data_width-1].
        data_bit_idx = crc_width + (data_width - 1 - step);
        data_mask    = bitshift(uint64(1), data_bit_idx);

        % feedback row = crc[crc_width-1] XOR data_bit
        feedback = bitxor(rows(crc_width), data_mask);

        % Shift LFSR one step: new_crc[i] = old_crc[i-1] XOR poly[i]*feedback
        new_rows = zeros(1, crc_width, 'uint64');
        for i = crc_width-1 : -1 : 1
            new_rows(i+1) = rows(i);                        % shift
            if bitand(bitshift(uint64(poly), -(i)), 1)      % poly bit i set?
                new_rows(i+1) = bitxor(new_rows(i+1), feedback);
            end
        end
        if bitand(uint64(poly), 1)                          % poly bit 0
            new_rows(1) = feedback;
        else
            new_rows(1) = uint64(0);
        end

        rows = new_rows;
    end

    % ------------------------------------------------------------------ %
    % 2. Generate Verilog text
    % ------------------------------------------------------------------ %
    lines = {};
    lines{end+1} = sprintf('// Auto-generated by gen_crc_assigns.m (MATLAB)');
    lines{end+1} = sprintf('// Polynomial : 0x%s   CRC width: %d   Data width: %d', ...
                            upper(poly_hex), crc_width, data_width);
    lines{end+1} = sprintf('// Processes %d bits per clock — no loop, no carry chain.', data_width);
    lines{end+1} = '';
    lines{end+1} = sprintf('module crc%d_par%d (', crc_width, data_width);
    lines{end+1} = sprintf('    input  wire [%d:0] crc_in,',  crc_width-1);
    lines{end+1} = sprintf('    input  wire [%d:0] data_in,', data_width-1);
    lines{end+1} = sprintf('    output wire [%d:0] crc_out',  crc_width-1);
    lines{end+1} = ');';
    lines{end+1} = '';

    for i = 0 : crc_width-1
        expr = build_xor_expr(rows(i+1), crc_width, data_width);
        lines{end+1} = sprintf('    assign crc_out[%2d] = %s;', i, expr);
    end

    lines{end+1} = '';
    lines{end+1} = 'endmodule';

    % ------------------------------------------------------------------ %
    % 3. Write to file
    % ------------------------------------------------------------------ %
    fid = fopen(out_file, 'w');
    if fid == -1
        error('gen_crc_assigns: cannot open "%s" for writing.', out_file);
    end
    for k = 1 : numel(lines)
        fprintf(fid, '%s\n', lines{k});
    end
    fclose(fid);

    fprintf('Written: %s\n', out_file);
    fprintf('  CRC-%d, polynomial 0x%s, %d-bit parallel\n', ...
            crc_width, upper(poly_hex), data_width);
    fprintf('  Frame latency: ceil(%d / %d) = %d cycles  (serial would need %d)\n', ...
            42000, data_width, ceil(42000/data_width), 42000);
end


% ======================================================================= %
% LOCAL HELPER — build the Verilog XOR expression for one CRC output bit
% ======================================================================= %
function expr = build_xor_expr(row_mask, crc_width, data_width)
% BUILD_XOR_EXPR  Return a Verilog string "crc_in[a] ^ data_in[b] ^ ..."
%   row_mask   – uint64 bit-mask of contributing input bits
%   crc_width  – number of CRC state bits
%   data_width – number of data bits per clock

    terms = {};

    % CRC state contributions: bits 0 .. crc_width-1
    for j = 0 : crc_width-1
        if bitand(bitshift(row_mask, -j), uint64(1))
            terms{end+1} = sprintf('crc_in[%d]', j);
        end
    end

    % Data input contributions: vector position (crc_width + k) maps to
    % data_in[data_width-1-k]  (because MSB entered first at step 0)
    for k = 0 : data_width-1
        bit_pos = crc_width + k;
        if bitand(bitshift(row_mask, -bit_pos), uint64(1))
            din_bit = data_width - 1 - k;
            terms{end+1} = sprintf('data_in[%d]', din_bit);
        end
    end

    if isempty(terms)
        expr = "1'b0";
    else
        expr = strjoin(terms, ' ^ ');
    end
end
